name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkfmt:
    runs-on: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v2
     
     - name: Cache jabba
       uses: actions/cache@v2.1.6
       with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba-cache-${{ hashFiles('**/workflows/scala.yml') }}
     
     - name: Cache SBT ivy cache
       uses: actions/cache@v2.1.6
       with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}  
    
     - name: Cache SBT
       uses: actions/cache@v2.1.6
       with:
         path: ~/.sbt
         key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}  
    
     - uses: olafurpg/setup-scala@v13
       with:
         java-version: graalvm@21.0.0=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0/graalvm-ce-java11-linux-amd64-21.0.0.tar.gz
    
     - name: Check format
       run: sbt checkfmt
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.14, 2.13.7]

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache jabba
      uses: actions/cache@v2.1.6
      with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba-cache-${{ hashFiles('**/workflows/scala.yml') }}
      
    - name: Cache SBT ivy cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    
    - name: Cache SBT
      uses: actions/cache@v2.1.6
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: graalvm@21.0.0=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0/graalvm-ce-java11-linux-amd64-21.0.0.tar.gz
    
    - name: Test
      run: sbt ++${{matrix.scala}} test
  
